### ISSUE TITLE
[C4GT Community]: Neo4J DB Integration

### ISSUE THREAD

**Issue by KDwevedi** [BharatSahAIyak/kg-markdown-enhancer#4]
## Description
Setup an accompanying Neo4J integration for the markdown enhancer.

## Goals
- [ ] Setup a [Dockerfile + compose file](https://neo4j.com/docs/operations-manual/current/docker/) for a local Neo4J instance
- [ ] Setup a [Javascript driver](https://neo4j.com/docs/javascript-manual/current/) for the Neo4J instance
  - [ ] Setup the ability to read the database
  - [ ] Setup the ability to create one of the [example datasets](https://neo4j.com/docs/getting-started/appendix/example-data/) for testing
- [ ] Setup a [visualisation](https://neo4j.com/developer-blog/graph-visualization-with-neo4j-using-neovis-js/)
  - [ ] We should be able to zoom into specific nodes.

### Expected Outcome

Neo4J DB integration and visualisation that:
- Updates dynamically when the DB is updated
- Can zoom into specified nodes in the graph

### Acceptance Criteria

- [ ] Visualisation updates dynamically 
- [ ] Visualisation has zoom-in functionality

### Implementation Details

Use docker to setup a local Neo4J instance
[Neo4J Docker docs](https://neo4j.com/docs/operations-manual/current/docker/)
Example Dockerfile:
```dockerfile
FROM neo4j:latest

ENV NEO4J_apoc_export_file_enabled=true \
    NEO4J_apoc_import_file_enabled=true \
    NEO4J_apoc_import_file_use__neo4j__config=true \
    NEO4J_dbms_security_procedures_unrestricted=apoc.* \
    NEO4J_PLUGINS=apoc-extended \
    NEO4J_AUTH=neo4j/testingInstance

EXPOSE 7474 7687
```

Example compose file:
```yaml
version: '3.8'
services:
  neo4j:
    build: ./database
    container_name: neo4j-instance
    environment:
      - NEO4J_AUTH=neo4j/testingInstance
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins
    restart: always

```

Use the [JS driver](https://neo4j.com/docs/javascript-manual/current/) to read the nodes.
To setup the graph visualisation: [neovis-js](https://neo4j.com/developer-blog/graph-visualization-with-neo4j-using-neovis-js/)

### Product Name

Bharat Sahaiyak

### Organisation Name

SamagraX

### Tech Skills Needed

Docker, JavaScript

### Mentor(s)

@KDwevedi 

### Complexity

High

### Category

Database, Frontend
